'use client';

import { useState } from 'react';
import { addToast } from './toast';
import { clsx } from 'clsx';
import {
  X,
  Maximize2,
  Minimize2,
  Pencil,
  Save,
  Download,
  Send,
} from 'lucide-react';

interface DocumentViewerProps {
  doc: {
    id: string;
    name: string;
    format: string;
    agent: string;
    department: string;
    date: string;
    status: string;
    content?: string;
  };
  onClose: () => void;
}

const mockContents: Record<string, string> = {
  '1': `# Proposal — NovaTech Solutions Enterprise Mobile App

**Prepared for:** Dan Cohen, NovaTech Solutions
**Prepared by:** MSApps Ltd.
**Date:** March 20, 2026
**Validity:** 30 days

---

## Executive Summary

MSApps proposes the design, development, and deployment of an enterprise mobile application for NovaTech Solutions's field operations team. The application will streamline fleet management, service scheduling, and real-time reporting.

## Project Scope

### Phase 1 — Discovery & Design (Weeks 1-4)
- Stakeholder interviews and requirements gathering
- UX research and user journey mapping
- UI design — 3 design concepts with 2 revision rounds
- Technical architecture document
- Prototype delivery

### Phase 2 — Development (Weeks 5-12)
- iOS and Android native development (React Native)
- Backend API development (Node.js + PostgreSQL)
- Fleet management module
- Service scheduling module
- Real-time reporting dashboard
- Push notifications system
- Offline-first data sync

### Phase 3 — QA & Launch (Weeks 13-16)
- Comprehensive QA testing
- Performance optimization
- App Store / Google Play submission
- Production deployment
- Knowledge transfer & documentation

## Pricing

| Item | Hours | Rate | Total |
|------|-------|------|-------|
| Discovery & Design | 120 | ₪250 | ₪30,000 |
| Development | 280 | ₪250 | ₪70,000 |
| QA & Launch | 60 | ₪250 | ₪15,000 |
| Project Management | 80 | ₪200 | ₪16,000 |
| **Total** | **540** | | **₪131,000** |

**Proposed Fixed Price:** ₪52,000 (introductory rate)

## Payment Terms

- 30% upon contract signing — ₪15,600
- 40% upon Phase 2 completion — ₪20,800
- 30% upon final delivery — ₪15,600

## Timeline

16 weeks from contract signing to production deployment.

---

*MSApps Ltd. | michal@msapps.co.il | +972-XXX-XXXXXXX*`,

  '2': `# Invoice #2026-024

**From:** MSApps Ltd.
**To:** Atlas Industries
**Date:** February 28, 2026
**Due Date:** March 30, 2026
**Status:** SENT

---

## Billing Summary

| Description | Hours | Rate | Amount |
|-------------|-------|------|--------|
| Senior Developer — App Module | 80 | ₪220 | ₪17,600 |
| UI/UX Designer | 32 | ₪200 | ₪6,400 |
| QA Engineer | 20 | ₪180 | ₪3,600 |
| Project Management | 10 | ₪200 | ₪2,000 |

---

**Subtotal:** ₪29,600
**Discount (5%):** -₪1,200
**Total Due:** ₪28,400

## Payment Details

Bank: First National Bank
Branch: 123
Account: 456789
Reference: INV-2026-024

---

*Payment is due within 30 days of invoice date.*`,

  '5': `# Daily Pipeline Brief — March 21, 2026

**Generated by:** Lead Pipeline Agent
**Time:** 08:12 AM

---

## Pipeline Summary

- **Total Active Leads:** 47
- **Hot Leads:** 4
- **Warm Leads:** 18
- **Cold Leads:** 25

## Hot Leads — Immediate Action Required

### 1. NovaTech Solutions ⚡
- **Value:** ₪52,000
- **Stage:** Proposal Sent (3 days ago)
- **Contact:** Dan Cohen
- **Action:** Follow up — no response to proposal
- **Next Step:** Call or send follow-up email

### 2. Meridian Digital ⚡
- **Value:** ₪85,000
- **Stage:** Pricing Requested
- **Contact:** David Goldstein
- **Action:** Generate and send proposal by Friday
- **Next Step:** Prepare enterprise proposal

### 3. Gett
- **Value:** TBD (discovery phase)
- **Stage:** Initial Inquiry
- **Contact:** Sarah Ben-David
- **Action:** First meeting scheduled Thursday
- **Next Step:** Prepare discovery presentation

### 4. Wix Studios
- **Value:** TBD (referred)
- **Stage:** New Lead
- **Contact:** Yonatan Raz (referred by Eli from CheckPoint)
- **Action:** High potential — existing client referral
- **Next Step:** Send intro email with case studies

## Calendar Updates

- ✅ Follow-up meeting with NovaTech Solutions — added for Wednesday 14:00
- ✅ Discovery call with Gett — confirmed for Thursday 10:00

## Metrics This Week

| Metric | Value | Trend |
|--------|-------|-------|
| New leads | 5 | ↑ 25% |
| Proposals sent | 2 | ↑ 100% |
| Meetings scheduled | 3 | → 0% |
| Conversion rate | 24% | ↑ 3% |

---

*Briefing sent to michal@msapps.co.il*`,

  '7': `# Monthly Billing Summary — February 2026

**Generated by:** Client Invoicing Agent
**Date:** February 28, 2026

---

## Overview

| | Count | Amount |
|--|-------|--------|
| Invoices Generated | 12 | ₪148,200 |
| Invoices Sent | 12 | ₪148,200 |
| Payments Received | 9 | ₪112,800 |
| Outstanding | 3 | ₪35,400 |

## Breakdown by Client

| Client | Hours | Amount | Status |
|--------|-------|--------|--------|
| Atlas Industries | 142 | ₪28,400 | Sent |
| Wix Studios | 180 | ₪36,000 | Sent |
| Gett | 96 | ₪19,200 | Sent |
| CheckPoint | 88 | ₪17,600 | Paid |
| Monday.com | 64 | ₪12,800 | Paid |
| Fiverr | 52 | ₪10,400 | Paid |
| Lemonade | 48 | ₪9,600 | Paid |
| FinBridge | 40 | ₪8,000 | Paid |
| Taboola | 36 | ₪7,200 | Paid |
| Other (3) | 30 | ₪6,000 | Paid |

## Revenue Trend

- January 2026: ₪132,500
- February 2026: ₪148,200 (+12%)
- Projected March: ₪155,000

---

*Report uploaded to Google Drive (Finance folder)*`,
};

export function DocumentViewer({ doc, onClose }: DocumentViewerProps) {
  const [fullscreen, setFullscreen] = useState(false);
  const [editing, setEditing] = useState(false);
  const [content, setContent] = useState(
    mockContents[doc.id] || `# ${doc.name}\n\n*Document content will be loaded from the agent output.*\n\nGenerated by ${doc.agent} on ${doc.date}.\n\nDepartment: ${doc.department}\nFormat: ${doc.format}\nStatus: ${doc.status}`
  );

  const handleSave = () => {
    setEditing(false);
    addToast(`${doc.name} saved`, 'success');
  };

  return (
    <div
      className={clsx(
        'fixed z-[80] bg-black/60',
        fullscreen ? 'inset-0' : 'inset-0 flex justify-end'
      )}
      onClick={onClose}
    >
      <div
        className={clsx(
          'bg-[#0d0d1a] flex flex-col animate-slide-right',
          fullscreen
            ? 'w-full h-full'
            : 'w-full max-w-3xl h-full border-l border-surface-border'
        )}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-surface-border shrink-0">
          <div className="min-w-0">
            <h3 className="text-base font-semibold text-white truncate">{doc.name}</h3>
            <div className="flex items-center gap-2 mt-1">
              <span className="text-xs text-gray-500">{doc.agent}</span>
              <span className="text-xs text-gray-600">·</span>
              <span className="text-xs text-gray-500">{doc.department}</span>
              <span className="text-xs text-gray-600">·</span>
              <span className="text-xs text-gray-500">{doc.date}</span>
              <span className={clsx(
                'text-[10px] font-semibold px-2 py-0.5 rounded-md uppercase',
                doc.format === 'PDF' ? 'bg-blue-500/20 text-blue-400' :
                doc.format === 'XLSX' ? 'bg-green-500/20 text-green-400' :
                'bg-purple-500/20 text-purple-400'
              )}>
                {doc.format}
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            {editing ? (
              <button
                onClick={handleSave}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-accent-400 bg-accent-500/10 hover:bg-accent-500/20 border border-accent-500/20"
              >
                <Save className="w-3.5 h-3.5" />
                Save
              </button>
            ) : (
              <button
                onClick={() => setEditing(true)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-brand-400 bg-brand-500/10 hover:bg-brand-500/20 border border-brand-500/20"
              >
                <Pencil className="w-3.5 h-3.5" />
                Edit
              </button>
            )}
            <button
              onClick={() => addToast(`Downloading ${doc.name}`, 'success')}
              className="p-2 rounded-lg text-gray-300 bg-surface-overlay hover:bg-surface-overlay/80 border border-surface-border"
              title="Download"
            >
              <Download className="w-3.5 h-3.5" />
            </button>
            {doc.status === 'draft' && (
              <button
                onClick={() => addToast(`Sending ${doc.name} to client`, 'success')}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-accent-400 bg-accent-500/10 hover:bg-accent-500/20 border border-accent-500/20"
              >
                <Send className="w-3.5 h-3.5" />
                Send
              </button>
            )}
            <button
              onClick={() => setFullscreen(!fullscreen)}
              className="p-2 rounded-lg text-gray-300 bg-surface-overlay hover:bg-surface-overlay/80 border border-surface-border"
              title={fullscreen ? 'Exit fullscreen' : 'Fullscreen'}
            >
              {fullscreen ? <Minimize2 className="w-3.5 h-3.5" /> : <Maximize2 className="w-3.5 h-3.5" />}
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg text-gray-300 hover:bg-surface-raised"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {editing ? (
            <textarea
              value={content}
              onChange={e => setContent(e.target.value)}
              className="w-full h-full min-h-[600px] bg-surface border border-surface-border rounded-xl p-5 text-sm text-gray-200 font-mono leading-relaxed resize-none focus:outline-none focus:border-brand-500"
            />
          ) : (
            <div className="prose-dark max-w-none">
              {content.split('\n').map((line, i) => {
                if (line.startsWith('# '))
                  return <h1 key={i} className="text-2xl font-bold text-white mb-4 mt-6 first:mt-0">{line.slice(2)}</h1>;
                if (line.startsWith('## '))
                  return <h2 key={i} className="text-lg font-semibold text-white mb-3 mt-6">{line.slice(3)}</h2>;
                if (line.startsWith('### '))
                  return <h3 key={i} className="text-base font-semibold text-white mb-2 mt-4">{line.slice(4)}</h3>;
                if (line.startsWith('---'))
                  return <hr key={i} className="border-surface-border my-6" />;
                if (line.startsWith('| ') && line.includes('|')) {
                  const cells = line.split('|').filter(c => c.trim());
                  const isHeader = i + 1 < content.split('\n').length && content.split('\n')[i + 1]?.match(/^\|[\s-|]+$/);
                  const isSeparator = line.match(/^\|[\s-|]+$/);
                  if (isSeparator) return null;
                  return (
                    <div key={i} className="flex border-b border-surface-border">
                      {cells.map((cell, ci) => (
                        <div key={ci} className={clsx(
                          'flex-1 px-3 py-2 text-xs',
                          isHeader ? 'font-semibold text-gray-300' : 'text-gray-400'
                        )}>
                          {cell.trim().replace(/\*\*(.*?)\*\*/g, '$1')}
                        </div>
                      ))}
                    </div>
                  );
                }
                if (line.startsWith('- '))
                  return <div key={i} className="flex items-start gap-2 text-sm text-gray-300 my-1 ml-2"><span className="text-brand-400 mt-0.5">•</span>{renderInline(line.slice(2))}</div>;
                if (line.startsWith('**') && line.endsWith('**'))
                  return <p key={i} className="text-sm font-semibold text-white my-1">{line.replace(/\*\*/g, '')}</p>;
                if (line.startsWith('*') && line.endsWith('*'))
                  return <p key={i} className="text-xs text-gray-500 italic my-1">{line.replace(/\*/g, '')}</p>;
                if (line.trim() === '')
                  return <div key={i} className="h-3" />;
                return <p key={i} className="text-sm text-gray-300 my-1 leading-relaxed">{renderInline(line)}</p>;
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function renderInline(text: string) {
  // Simple bold/italic rendering
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**'))
      return <strong key={i} className="text-white font-semibold">{part.slice(2, -2)}</strong>;
    return <span key={i}>{part}</span>;
  });
}
