import { Agent, ExecutionLog, DepartmentMetrics } from './types';

export const agents: Agent[] = [
  {
    id: 'lead-pipeline',
    name: 'Lead Pipeline',
    department: 'Sales',
    description: 'Pulls new leads from Salesforce and Angi/HomeAdvisor. Scores, assigns to reps by territory, sends SMS confirmation, books in-home consultations.',
    status: 'running',
    schedule: 'Every 30 minutes',
    lastRun: '2026-03-27T14:30:00Z',
    nextRun: '2026-03-27T15:00:00Z',
    icon: 'target',
    metrics: [
      { label: 'Active Leads', value: 142, trend: 15 },
      { label: 'Qualified Today', value: 18, trend: 22 },
      { label: 'Conversion Rate', value: '24%', trend: 5 },
    ],
  },
  {
    id: 'lead-discovery',
    name: 'Lead Discovery',
    department: 'Sales',
    description: 'Searches Angi, HomeAdvisor, Thumbtack, and Nextdoor for new home improvement requests. Monitors permit filings and new homeowner data.',
    status: 'idle',
    schedule: 'Every day at 06:00',
    lastRun: '2026-03-27T06:00:00Z',
    nextRun: '2026-03-28T06:00:00Z',
    icon: 'search',
    metrics: [
      { label: 'Sources Scanned', value: 5, trend: 0 },
      { label: 'New Prospects', value: 34, trend: 12 },
      { label: 'Avg Lead Score', value: 72, trend: 8 },
    ],
  },
  {
    id: 'campaign-manager',
    name: 'Campaign Manager',
    department: 'Marketing',
    description: 'Manages Google Ads and Meta Ads campaigns. Adjusts bids based on Salesforce close rates, pauses low performers, scales winners.',
    status: 'idle',
    schedule: 'Every day at 07:00',
    lastRun: '2026-03-27T07:00:00Z',
    nextRun: '2026-03-28T07:00:00Z',
    icon: 'megaphone',
    metrics: [
      { label: 'Active Campaigns', value: 24, trend: 8 },
      { label: 'ROAS', value: '4.2x', trend: 12 },
      { label: 'Cost per Lead', value: '$96', trend: -15 },
    ],
  },
  {
    id: 'campaign-performance',
    name: 'Campaign Performance',
    department: 'Marketing',
    description: 'Weekly deep attribution report: Ad → Click → Lead → Appointment → Proposal → Closed-Won. Calculates true CPA by channel.',
    status: 'scheduled',
    schedule: 'Every Monday at 06:00',
    lastRun: '2026-03-23T06:00:00Z',
    nextRun: '2026-03-30T06:00:00Z',
    icon: 'trending-up',
    metrics: [
      { label: 'Channels Tracked', value: 6, trend: 0 },
      { label: 'Blended CPA', value: '$118', trend: -8 },
      { label: 'Revenue Attributed', value: '$482K', trend: 22 },
    ],
  },
  {
    id: 'seo-health',
    name: 'SEO Health Monitor',
    department: 'Marketing',
    description: 'Tracks Google Search Console rankings, Core Web Vitals, Google Business Profile reviews, and competitor keyword positions.',
    status: 'idle',
    schedule: 'Every day at 05:30',
    lastRun: '2026-03-27T05:30:00Z',
    nextRun: '2026-03-28T05:30:00Z',
    icon: 'search',
    metrics: [
      { label: 'Keywords Top 10', value: 28, trend: 10 },
      { label: 'GBP Rating', value: '4.8★', trend: 2 },
      { label: 'Organic Leads', value: 45, trend: 18 },
    ],
  },
  {
    id: 'project-management',
    name: 'Project Tracker',
    department: 'Operations',
    description: 'Syncs Monday.com and BuilderTrend for active renovation projects. Tracks milestones, flags delays, sends homeowner SMS updates.',
    status: 'running',
    schedule: 'Every 2 hours',
    lastRun: '2026-03-27T14:00:00Z',
    nextRun: '2026-03-27T16:00:00Z',
    icon: 'clipboard-list',
    metrics: [
      { label: 'Active Projects', value: 38, trend: 5 },
      { label: 'On Schedule', value: '84%', trend: 3 },
      { label: 'Avg Duration', value: '18 days', trend: -8 },
    ],
  },
  {
    id: 'subcontractor-mgmt',
    name: 'Subcontractor Manager',
    department: 'Operations',
    description: 'Maintains sub database, monitors license/insurance expiry, tracks performance ratings, handles auto-assignment to projects.',
    status: 'idle',
    schedule: 'Every day at 07:30',
    lastRun: '2026-03-27T07:30:00Z',
    nextRun: '2026-03-28T07:30:00Z',
    icon: 'users',
    metrics: [
      { label: 'Active Subs', value: 84, trend: 6 },
      { label: 'Avg Rating', value: '4.4★', trend: 3 },
      { label: 'Expiring Certs', value: 3, trend: -25 },
    ],
  },
  {
    id: 'sub-shopping',
    name: 'Subcontractor Shopping',
    department: 'Operations',
    description: 'Searches for new subs when capacity needed. Compares rates, reviews, licensing, and generates comparison matrices.',
    status: 'idle',
    schedule: 'Every Wednesday at 08:00',
    lastRun: '2026-03-25T08:00:00Z',
    nextRun: '2026-04-01T08:00:00Z',
    icon: 'search',
    metrics: [
      { label: 'Candidates Found', value: 12, trend: 20 },
      { label: 'Avg Rate/hr', value: '$72', trend: 3 },
      { label: 'Vetted This Month', value: 5, trend: 67 },
    ],
  },
  {
    id: 'supplier-shopping',
    name: 'Supplier Shopping',
    department: 'Procurement',
    description: 'Compares material pricing across Home Depot Pro, ABC Supply, and local distributors. Tracks bulk discounts and lead times.',
    status: 'idle',
    schedule: 'Every Wednesday at 09:00',
    lastRun: '2026-03-25T09:00:00Z',
    nextRun: '2026-04-01T09:00:00Z',
    icon: 'package',
    metrics: [
      { label: 'Suppliers Tracked', value: 18, trend: 12 },
      { label: 'Avg Savings', value: '11%', trend: 4 },
      { label: 'Price Alerts', value: 6, trend: -10 },
    ],
  },
  {
    id: 'payroll-commissions',
    name: 'Payroll & Commissions',
    department: 'Finance',
    description: 'Calculates tiered sales commissions (8-12%), project manager bonuses, and sub payments. Reconciles with QuickBooks and Gusto.',
    status: 'idle',
    schedule: 'Bi-weekly Friday at 06:00',
    lastRun: '2026-03-14T06:00:00Z',
    nextRun: '2026-03-28T06:00:00Z',
    icon: 'wallet',
    metrics: [
      { label: 'Total Payroll', value: '$186K', trend: 8 },
      { label: 'Commissions Due', value: '$42K', trend: 15 },
      { label: 'Sub Payments', value: '$94K', trend: 5 },
    ],
  },
  {
    id: 'sales-team',
    name: 'Sales Performance',
    department: 'Sales',
    description: 'Daily Salesforce pipeline snapshot per rep. Tracks close rates, speed-to-lead, stuck deals, and generates morning dashboard for VP Sales.',
    status: 'idle',
    schedule: 'Every day at 08:00',
    lastRun: '2026-03-27T08:00:00Z',
    nextRun: '2026-03-28T08:00:00Z',
    icon: 'target',
    metrics: [
      { label: 'Pipeline Value', value: '$2.4M', trend: 18 },
      { label: 'Close Rate', value: '38%', trend: 6 },
      { label: 'Avg Deal Size', value: '$32K', trend: 10 },
    ],
  },
  {
    id: 'financing-engine',
    name: 'Financing Engine',
    department: 'Finance',
    description: 'Triggers GreenSky/Hearth preapprovals on new proposals. Presents financing options, tracks loan status, alerts on expiring preapprovals.',
    status: 'running',
    schedule: 'Real-time + Daily 10:00',
    lastRun: '2026-03-27T14:22:00Z',
    nextRun: '2026-03-27T14:45:00Z',
    icon: 'credit-card',
    metrics: [
      { label: 'Preapprovals Today', value: 7, trend: 40 },
      { label: 'Attachment Rate', value: '64%', trend: 8 },
      { label: 'Avg Loan Amount', value: '$28K', trend: 12 },
    ],
  },
  {
    id: 'receipts-collector',
    name: 'Receipts Collector',
    department: 'Finance',
    description: 'Scans emails and Google Drive for sub/supplier invoices. OCR extracts details, matches to projects, categorizes in QuickBooks.',
    status: 'idle',
    schedule: 'Every day at 09:00',
    lastRun: '2026-03-27T09:00:00Z',
    nextRun: '2026-03-28T09:00:00Z',
    icon: 'receipt',
    metrics: [
      { label: 'Receipts Today', value: 14, trend: 10 },
      { label: 'Auto-Matched', value: '91%', trend: 5 },
      { label: 'Flagged', value: 2, trend: -50 },
    ],
  },
  {
    id: 'salesforce-sync',
    name: 'Salesforce Sync',
    department: 'Operations',
    description: 'Ensures data consistency across Salesforce, QuickBooks, Monday.com, and BuilderTrend. Auto-creates projects on Closed-Won deals.',
    status: 'running',
    schedule: 'Every hour',
    lastRun: '2026-03-27T14:00:00Z',
    nextRun: '2026-03-27T15:00:00Z',
    icon: 'refresh-cw',
    metrics: [
      { label: 'Records Synced', value: '2,847', trend: 3 },
      { label: 'Data Quality', value: '94%', trend: 2 },
      { label: 'Sync Errors', value: 1, trend: -75 },
    ],
  },
  {
    id: 'social-content',
    name: 'Social & Reviews',
    department: 'Marketing',
    description: 'Generates social media posts (before/after photos, tips, testimonials). Monitors and drafts responses to Google/Yelp reviews.',
    status: 'idle',
    schedule: 'Mon, Wed, Fri at 08:00',
    lastRun: '2026-03-26T08:00:00Z',
    nextRun: '2026-03-28T08:00:00Z',
    icon: 'megaphone',
    metrics: [
      { label: 'Posts Scheduled', value: 6, trend: 20 },
      { label: 'Engagement Rate', value: '4.8%', trend: 15 },
      { label: 'New Reviews', value: 8, trend: 33 },
    ],
  },
  {
    id: 'morning-briefing',
    name: 'CEO Morning Briefing',
    department: 'Executive',
    description: 'Compiles executive daily summary: sales wins, project risks, cash position, marketing metrics, team issues. Delivered via email + SMS.',
    status: 'idle',
    schedule: 'Every day at 07:00',
    lastRun: '2026-03-27T07:00:00Z',
    nextRun: '2026-03-28T07:00:00Z',
    icon: 'clipboard-list',
    metrics: [
      { label: 'Departments', value: 6, trend: 0 },
      { label: 'Action Items', value: 4, trend: -20 },
      { label: 'Delivery', value: 'Email+SMS', trend: 0 },
    ],
  },
  {
    id: 'digital-health',
    name: 'Digital Health',
    department: 'Marketing',
    description: 'Pulls GA4 data on sessions, conversions, funnel drop-offs. Monitors form submissions, chat widget, financing widget, and tracking pixels.',
    status: 'idle',
    schedule: 'Every day at 06:30',
    lastRun: '2026-03-27T06:30:00Z',
    nextRun: '2026-03-28T06:30:00Z',
    icon: 'activity',
    metrics: [
      { label: 'Daily Sessions', value: '3,240', trend: 12 },
      { label: 'Conv. Rate', value: '3.8%', trend: 8 },
      { label: 'Bounce Rate', value: '42%', trend: -5 },
    ],
  },
];

export const executionLogs: ExecutionLog[] = [
  {
    id: 'log-001',
    agentId: 'lead-pipeline',
    agentName: 'Lead Pipeline',
    department: 'Sales',
    startedAt: '2026-03-27T14:30:00Z',
    completedAt: '2026-03-27T14:42:15Z',
    status: 'success',
    summary: 'Processed 24 new leads — 6 hot (>$25K), assigned to reps, 4 in-home consultations booked',
    details: [
      'Pulled 24 new leads from Angi and HomeAdvisor',
      'Lead scoring: 6 hot leads ($25K+), 8 warm, 10 cold',
      'Assigned by territory: Sarah (River Oaks: $45K kitchen), Marcus (Montrose: $32K bathroom)',
      'Sent SMS to 4 leads with consultation booking links',
      'Updated Salesforce pipeline with touch notes',
      'Sent briefing to VP Sales',
    ],
    outputCount: 24,
    output: [
      {
        type: 'summary',
        title: 'Lead intake complete',
        items: [
          { icon: 'check', text: '24 new leads processed from Angi + HomeAdvisor' },
          { icon: 'fire', text: '6 HOT leads (>$25K value) — assigned immediately' },
          { icon: 'phone', text: '4 in-home consultations booked via SMS confirmation' },
        ],
      },
      {
        type: 'results',
        title: 'Hot leads assigned',
        items: [
          { icon: 'user', text: 'Sarah Chen — River Oaks kitchen remodel ($45K)', highlight: true, actions: [
            { label: 'View Lead', style: 'primary', icon: 'eye' },
            { label: 'Schedule Consultation', style: 'success', icon: 'calendar' },
          ] },
          { icon: 'user', text: 'Marcus Johnson — Montrose bathroom ($32K)', highlight: true, actions: [
            { label: 'View Lead', style: 'primary', icon: 'eye' },
            { label: 'Schedule Consultation', style: 'success', icon: 'calendar' },
          ] },
          { icon: 'user', text: 'Derek Mills — Memorial whole home ($38K)', highlight: true, actions: [
            { label: 'View Lead', style: 'primary', icon: 'eye' },
            { label: 'Schedule Consultation', style: 'success', icon: 'calendar' },
          ] },
        ],
      },
      {
        type: 'attention',
        title: 'Needs your attention',
        items: [
          { icon: 'alert', text: 'Sarah — hot lead assigned but no contact yet (2 hours old)', highlight: true, actions: [
            { label: 'View Details', style: 'primary', icon: 'eye' },
            { label: 'Send SMS', style: 'success', icon: 'send' },
          ] },
          { icon: 'alert', text: '1 lead booked consultation but failed SMS delivery — email sent as backup', highlight: true, actions: [
            { label: 'View Lead', style: 'primary', icon: 'eye' },
            { label: 'Resend SMS', style: 'success', icon: 'send' },
          ] },
        ],
      },
    ],
  },
  {
    id: 'log-002',
    agentId: 'sales-team',
    agentName: 'Sales Performance',
    department: 'Sales',
    startedAt: '2026-03-27T08:00:00Z',
    completedAt: '2026-03-27T08:11:22Z',
    status: 'success',
    summary: 'Daily pipeline scan — $2.4M pipeline, 3 deals stuck >7 days, leaderboard sent to VP Sales',
    details: [
      'Scanned 8 sales rep pipelines in Salesforce',
      'Pipeline snapshot: $2.4M (↑18% from yesterday)',
      'Identified 3 deals stuck >7 days: Jenkins kitchen, Martinez bathroom, Thompson roofing',
      'Close rates by rep: Sarah 42%, Marcus 38%, Derek 24% (↓14% this month)',
      'Generated daily leaderboard and action items',
      'Sent briefing to VP Sales via email + Slack',
    ],
    outputCount: 8,
    output: [
      {
        type: 'summary',
        title: 'Pipeline snapshot',
        items: [
          { icon: 'trending-up', text: 'Pipeline: $2.4M (↑18% trending ↑)' },
          { icon: 'target', text: '142 active leads across 8 sales reps' },
          { icon: 'check', text: 'Close rate: 38% avg (best: Sarah 42%, worst: Derek 24%)' },
        ],
      },
      {
        type: 'results',
        title: 'Sales leaderboard',
        items: [
          { icon: 'user', text: 'Sarah Chen', subtitle: '⭐ Top performer · 12 proposals · 42% close rate · $380K pipeline' },
          { icon: 'user', text: 'Marcus Johnson', subtitle: '8 proposals · 38% close rate · $320K pipeline' },
          { icon: 'user', text: 'Jennifer Rodriguez', subtitle: '7 proposals · 40% close rate · $280K pipeline' },
          { icon: 'user', text: 'Derek Mills', subtitle: '⚠ Underperforming · 6 proposals · 24% close rate · $190K pipeline' },
        ],
      },
      {
        type: 'attention',
        title: 'Stuck deals (>7 days)',
        items: [
          { icon: 'alert', text: 'Jenkins Kitchen — $52K proposal, sent March 19, no response', highlight: true, tag: '$52K', tagColor: 'red', actions: [
            { label: 'View Deal', style: 'primary', icon: 'eye' },
            { label: 'Send Follow-up', style: 'success', icon: 'send' },
          ] },
          { icon: 'alert', text: 'Martinez Bathroom — $38K proposal, sent March 18, client went silent', highlight: true, tag: '$38K', tagColor: 'red', actions: [
            { label: 'View Deal', style: 'primary', icon: 'eye' },
            { label: 'Call Client', style: 'success', icon: 'phone' },
          ] },
          { icon: 'alert', text: 'Thompson Roofing — $42K, in negotiation for 9 days, needs decision', highlight: true, tag: '$42K', tagColor: 'red', actions: [
            { label: 'View Deal', style: 'primary', icon: 'eye' },
            { label: 'Schedule Call', style: 'success', icon: 'calendar' },
          ] },
        ],
      },
    ],
  },
  {
    id: 'log-003',
    agentId: 'project-management',
    agentName: 'Project Tracker',
    department: 'Operations',
    startedAt: '2026-03-27T14:00:00Z',
    completedAt: '2026-03-27T14:08:45Z',
    status: 'success',
    summary: '38 active projects monitored — 2 behind schedule, homeowner updates sent for 5 milestone completions',
    details: [
      'Synced 38 active projects from Monday.com + BuilderTrend',
      'Status check: 32 on-time (84%), 4 at-risk (11%), 2 delayed (5%)',
      'Jenkins Kitchen: 4 days behind (countertop templating delayed)',
      'Sent SMS updates to 5 homeowners on milestone completions',
      'Flagged two projects for crew review',
      'Updated Salesforce opportunity timelines',
    ],
    outputCount: 38,
    output: [
      {
        type: 'summary',
        title: 'Project status',
        items: [
          { icon: 'check', text: '38 active projects tracked across Houston metro' },
          { icon: 'trending-up', text: '84% on-time delivery rate' },
          { icon: 'phone', text: '5 homeowner milestone SMS sent' },
        ],
      },
      {
        type: 'results',
        title: 'On-schedule highlights',
        items: [
          { icon: 'check', text: 'Williams Window Replacement — Completed March 24 (2 days early)' },
          { icon: 'check', text: 'Park Roofing Project — On track, completion March 30' },
          { icon: 'check', text: 'Thompson Flooring — Paint phase complete, tile install starting tomorrow' },
          { icon: 'check', text: 'Henderson Whole Home — Week 8 of 12, all trades on schedule' },
        ],
      },
      {
        type: 'attention',
        title: 'Projects behind schedule',
        items: [
          { icon: 'alert', text: 'Jenkins Kitchen — 4 days behind, countertop templating delayed by supplier', highlight: true, tag: 'DELAYED', tagColor: 'red', actions: [
            { label: 'View Project', style: 'primary', icon: 'eye' },
            { label: 'Contact Client', style: 'success', icon: 'phone' },
            { label: 'Resolve Issue', style: 'success', icon: 'checkmark' },
          ] },
          { icon: 'alert', text: 'Garcia Bathroom Remodel — 2 days behind, drywall crew no-show Tuesday', highlight: true, tag: 'AT-RISK', tagColor: 'orange', actions: [
            { label: 'View Project', style: 'primary', icon: 'eye' },
            { label: 'Reschedule Crew', style: 'success', icon: 'calendar' },
          ] },
        ],
      },
    ],
  },
  {
    id: 'log-004',
    agentId: 'campaign-manager',
    agentName: 'Campaign Manager',
    department: 'Marketing',
    startedAt: '2026-03-27T07:00:00Z',
    completedAt: '2026-03-27T07:15:30Z',
    status: 'success',
    summary: 'Adjusted 24 campaigns — paused 3 low performers (CPA>$180), scaled 2 winners (+15% budget)',
    details: [
      'Analyzed 24 active Google Ads + Meta campaigns',
      'Paused 3 underperformers: Kitchen Remodel (CPA $220), Bathroom Houston (CPA $195), Old Roof (CPA $210)',
      'Scaled 2 winners: Kitchen Remodel River Oaks (CPA $78), Whole Home Remodel (CPA $92)',
      'Adjusted bids on 12 campaigns based on conversion rates',
      'Added $8,500 budget to high-performers',
      'Generated daily performance briefing for marketing team',
    ],
    outputCount: 24,
    output: [
      {
        type: 'summary',
        title: 'Campaign optimization complete',
        items: [
          { icon: 'check', text: '24 campaigns analyzed and adjusted' },
          { icon: 'trending-up', text: 'Blended ROAS: 4.2x (↑12%)' },
          { icon: 'money', text: 'Overall CPA: $96 (↓15%)' },
        ],
      },
      {
        type: 'results',
        title: 'Winners (scaled +15%)',
        items: [
          { icon: 'trending-up', text: 'Kitchen Remodel River Oaks — CPA $78, +15% budget to $5K/day' },
          { icon: 'trending-up', text: 'Whole Home Remodel — CPA $92, +15% budget to $3.5K/day' },
        ],
      },
      {
        type: 'attention',
        title: 'Paused underperformers',
        items: [
          { icon: 'pause', text: 'Kitchen Remodel Generic — CPA $220 (↑40% from target)', tag: 'PAUSED', tagColor: 'red', actions: [
            { label: 'View Campaign', style: 'primary', icon: 'eye' },
            { label: 'Archive', style: 'secondary', icon: 'trash' },
          ] },
          { icon: 'pause', text: 'Bathroom Houston (old creative) — CPA $195', tag: 'PAUSED', tagColor: 'red', actions: [
            { label: 'View Campaign', style: 'primary', icon: 'eye' },
            { label: 'Refresh Creative', style: 'success', icon: 'refresh' },
          ] },
          { icon: 'pause', text: 'Old Roof Campaign — CPA $210 (seasonal decline)', tag: 'PAUSED', tagColor: 'red', actions: [
            { label: 'View Campaign', style: 'primary', icon: 'eye' },
            { label: 'Resume', style: 'success', icon: 'play' },
          ] },
        ],
      },
    ],
  },
  {
    id: 'log-005',
    agentId: 'financing-engine',
    agentName: 'Financing Engine',
    department: 'Finance',
    startedAt: '2026-03-27T14:22:00Z',
    completedAt: '2026-03-27T14:31:18Z',
    status: 'success',
    summary: 'Processed 7 preapproval requests — 5 approved (GreenSky), 1 pending (Hearth), 1 declined',
    details: [
      'Processed 7 new financing requests from sales team',
      'GreenSky approvals: 5 approved (Martinez $38K, Williams $18K, Johnson $22K, Lee $32K, Brown $25K)',
      'Hearth application: 1 pending (Garcia $28K, decision within 24 hours)',
      'Credit-denied: 1 (Thompson $35K, suggested GreenSky Business line)',
      'Sent approval notifications and documents to homeowners',
      'Updated Salesforce financing pipeline',
    ],
    outputCount: 7,
    output: [
      {
        type: 'summary',
        title: 'Preapproval processing complete',
        items: [
          { icon: 'check', text: '7 preapproval requests processed' },
          { icon: 'check', text: '5 approved via GreenSky' },
          { icon: 'clock', text: '1 pending (Hearth) — decision tomorrow' },
        ],
      },
      {
        type: 'results',
        title: 'Approved financing',
        items: [
          { icon: 'credit-card', text: 'Martinez Family — $38K bathroom, GreenSky approved' },
          { icon: 'credit-card', text: 'Williams Family — $18K window replacement, GreenSky approved' },
          { icon: 'credit-card', text: 'Johnson Family — $22K kitchen cabinets, GreenSky approved' },
          { icon: 'credit-card', text: 'Lee Family — $32K bathroom remodel, GreenSky approved' },
          { icon: 'credit-card', text: 'Brown Family — $25K roof replacement, GreenSky approved' },
        ],
      },
      {
        type: 'attention',
        title: 'Pending & Issues',
        items: [
          { icon: 'clock', text: 'Garcia Family — $28K kitchen via Hearth, decision within 24 hours', highlight: true, tag: 'PENDING', tagColor: 'yellow', actions: [
            { label: 'View Application', style: 'primary', icon: 'eye' },
            { label: 'Follow Up', style: 'success', icon: 'phone' },
          ] },
          { icon: 'alert', text: 'Thompson Project — $35K denied by standard credit check, suggested GreenSky Business line', highlight: true, tag: 'DECLINED', tagColor: 'red', actions: [
            { label: 'View Details', style: 'primary', icon: 'eye' },
            { label: 'Suggest Alternative', style: 'success', icon: 'send' },
          ] },
        ],
      },
    ],
  },
  {
    id: 'log-006',
    agentId: 'receipts-collector',
    agentName: 'Receipts Collector',
    department: 'Finance',
    startedAt: '2026-03-27T09:00:00Z',
    completedAt: '2026-03-27T09:19:45Z',
    status: 'success',
    summary: 'Scanned 14 receipts — 12 auto-matched to projects, 2 flagged (no matching PO)',
    details: [
      'Scanned 14 supplier/sub invoices from email and Google Drive',
      'OCR extracted: vendor, amount, invoice date, line items',
      'Auto-matched 12 to open POs and projects (91% match rate)',
      'Uploaded receipts to QuickBooks projects',
      'Flagged 2 invoices: ABC Supply $8,400 (no matching PO), Home Depot $1,200 (amount mismatch)',
      'Sent summary to finance team',
    ],
    outputCount: 14,
    output: [
      {
        type: 'summary',
        title: 'Receipt scanning complete',
        items: [
          { icon: 'check', text: '14 invoices scanned and processed' },
          { icon: 'check', text: '12 auto-matched to projects (91% success)' },
          { icon: 'alert', text: '2 flagged for manual review' },
        ],
      },
      {
        type: 'results',
        title: 'Successfully matched receipts',
        items: [
          { icon: 'check', text: 'Elite Electric invoice $4,200 → Jenkins Kitchen project' },
          { icon: 'check', text: 'ABC Tile invoice $6,800 → Martinez Bathroom project' },
          { icon: 'check', text: '10 other invoices matched to active projects' },
        ],
      },
      {
        type: 'attention',
        title: 'Flagged for review',
        items: [
          { icon: 'alert', text: 'ABC Supply invoice $8,400 — No matching PO found', highlight: true, tag: '$8,400', tagColor: 'red', actions: [
            { label: 'View Invoice', style: 'primary', icon: 'eye' },
            { label: 'Find PO', style: 'success', icon: 'search' },
            { label: 'Create PO', style: 'success', icon: 'plus' },
          ] },
          { icon: 'alert', text: 'Home Depot receipt $1,200 — Amount mismatch with PO ($1,450)', highlight: true, tag: '$1,200', tagColor: 'orange', actions: [
            { label: 'View Receipt', style: 'primary', icon: 'eye' },
            { label: 'Contact Vendor', style: 'success', icon: 'phone' },
          ] },
        ],
      },
    ],
  },
  {
    id: 'log-007',
    agentId: 'subcontractor-mgmt',
    agentName: 'Subcontractor Manager',
    department: 'Operations',
    startedAt: '2026-03-27T07:30:00Z',
    completedAt: '2026-03-27T07:41:12Z',
    status: 'success',
    summary: 'Daily check: 3 insurance certs expiring within 30 days, 2 subs rated below 3.5 threshold',
    details: [
      'Daily expiry check on 84 active subcontractors',
      'Insurance certificates expiring within 30 days: 3 subs (Elite Electric March 29, ABC Plumbing April 2, Premier HVAC April 8)',
      'Performance review: 2 subs below 3.5 rating threshold',
      'Sent renewal reminders to 3 subs with expiring insurance',
      'Flagged performance issues for discussion',
      'Generated subcontractor management briefing',
    ],
    outputCount: 84,
    output: [
      {
        type: 'summary',
        title: 'Subcontractor daily check',
        items: [
          { icon: 'check', text: '84 active subcontractors reviewed' },
          { icon: 'alert', text: '3 insurance certificates expiring within 30 days' },
          { icon: 'warning', text: '2 subs rated below 3.5 stars' },
        ],
      },
      {
        type: 'results',
        title: 'Certified & performing well',
        items: [
          { icon: 'check', text: 'Elite Flooring — 4.8★ rating, 28 projects completed, fully insured through 2027' },
          { icon: 'check', text: 'Master Plumbing — 4.6★ rating, 15 projects completed, insurance valid' },
          { icon: 'check', text: '82 other subs in good standing' },
        ],
      },
      {
        type: 'attention',
        title: 'Expiring certifications',
        items: [
          { icon: 'alert', text: 'Elite Electric — Insurance expires March 29 (2 days!), assigned to 3 active projects', highlight: true, tag: 'URGENT', tagColor: 'red', actions: [
            { label: 'View Sub', style: 'primary', icon: 'eye' },
            { label: 'Send Renewal Reminder', style: 'success', icon: 'send' },
            { label: 'Pull from Jobs', style: 'warning', icon: 'user-minus' },
          ] },
          { icon: 'alert', text: 'ABC Plumbing — Insurance expires April 2 (6 days)', highlight: true, tag: 'EXPIRING', tagColor: 'orange', actions: [
            { label: 'View Sub', style: 'primary', icon: 'eye' },
            { label: 'Send Renewal Reminder', style: 'success', icon: 'send' },
          ] },
          { icon: 'warning', text: 'Quickfix Repairs — Rating dropped to 3.2★ (5 recent complaints)', highlight: true, tag: 'REVIEW', tagColor: 'red', actions: [
            { label: 'View Sub', style: 'primary', icon: 'eye' },
            { label: 'Review Complaints', style: 'success', icon: 'eye' },
            { label: 'Pause Assignments', style: 'warning', icon: 'pause' },
          ] },
          { icon: 'warning', text: 'Budget HVAC — Rating 3.3★ (slow response times on calls)', highlight: true, tag: 'REVIEW', tagColor: 'orange', actions: [
            { label: 'View Sub', style: 'primary', icon: 'eye' },
            { label: 'Schedule Coaching', style: 'success', icon: 'calendar' },
          ] },
        ],
      },
    ],
  },
  {
    id: 'log-008',
    agentId: 'payroll-commissions',
    agentName: 'Payroll & Commissions',
    department: 'Finance',
    startedAt: '2026-03-14T06:00:00Z',
    completedAt: '2026-03-14T06:28:42Z',
    status: 'success',
    summary: 'Bi-weekly payroll: $186K total — $42K commissions (8 reps), $94K sub payments, $50K salaries',
    details: [
      'Calculated bi-weekly payroll for 8 sales reps + 2 project managers + 1 operations lead',
      'Sales commissions: 8 reps at tiered rates (8-12% based on pipeline)',
      'Project manager bonuses: 2 managers at $2,500 each',
      'Subcontractor payments: 14 subs from milestone completions',
      'Salary payroll: 11 employees through Gusto',
      'Reconciled with Salesforce pipeline and Monday.com project completions',
      'Generated commission statements and sub payment logs',
      'Pushed payroll to Gusto for processing',
    ],
    outputCount: 14,
    output: [
      {
        type: 'summary',
        title: 'Bi-weekly payroll processed',
        items: [
          { icon: 'wallet', text: 'Total payroll: $186,000 (bi-weekly)' },
          { icon: 'trending-up', text: 'Sales commissions: $42,000 (8 reps, 8-12% tiered)' },
          { icon: 'users', text: 'Sub payments: $94,000 (14 vendors)' },
          { icon: 'user', text: 'Salaries: $50,000 (11 employees)' },
        ],
      },
      {
        type: 'results',
        title: 'Sales commission breakdown',
        items: [
          { icon: 'award', text: 'Sarah Chen — $6,400 (12% on $350K pipeline — top performer)' },
          { icon: 'award', text: 'Marcus Johnson — $4,800 (10% on $320K pipeline)' },
          { icon: 'award', text: 'Jennifer Rodriguez — $4,200 (10% on $280K pipeline)' },
          { icon: 'user', text: 'Derek Mills — $2,100 (8% on $190K pipeline)' },
          { icon: 'user', text: '4 other reps — $24,500 total' },
        ],
      },
      {
        type: 'attention',
        title: 'Subcontractor top payouts',
        items: [
          { icon: 'wallet', text: 'Elite Electric — $8,400 (Jenkins Kitchen milestone)' },
          { icon: 'wallet', text: 'ABC Tile — $6,800 (Martinez Bathroom milestone)' },
          { icon: 'wallet', text: '12 other subs — $78,800' },
        ],
      },
    ],
  },
  {
    id: 'log-009',
    agentId: 'seo-health',
    agentName: 'SEO Health Monitor',
    department: 'Marketing',
    startedAt: '2026-03-27T05:30:00Z',
    completedAt: '2026-03-27T05:52:18Z',
    status: 'success',
    summary: 'Rankings update — 4 keywords improved, houston kitchen remodel now #3, 2 new competitor threats',
  },
  {
    id: 'log-010',
    agentId: 'salesforce-sync',
    agentName: 'Salesforce Sync',
    department: 'Operations',
    startedAt: '2026-03-27T14:00:00Z',
    completedAt: '2026-03-27T14:04:33Z',
    status: 'success',
    summary: 'Hourly sync — 3 new Closed-Won deals pushed to Monday.com, 2 invoices created in QuickBooks',
  },
  {
    id: 'log-011',
    agentId: 'morning-briefing',
    agentName: 'CEO Morning Briefing',
    department: 'Executive',
    startedAt: '2026-03-27T07:00:00Z',
    completedAt: '2026-03-27T07:12:45Z',
    status: 'success',
    summary: 'Executive summary compiled — 4 action items flagged for CEO attention',
  },
  {
    id: 'log-012',
    agentId: 'social-content',
    agentName: 'Social & Reviews',
    department: 'Marketing',
    startedAt: '2026-03-26T08:00:00Z',
    completedAt: '2026-03-26T08:18:30Z',
    status: 'success',
    summary: '3 posts scheduled, responded to 2 Google reviews (1 negative — draft pending CEO approval)',
  },
];

export const departmentMetrics: DepartmentMetrics[] = [
  {
    department: 'Sales',
    icon: 'target',
    kpis: [
      { label: 'Pipeline Value', value: '$2.4M', trend: 18, sparkline: [1.6, 1.8, 1.95, 2.1, 2.25, 2.35, 2.4] },
      { label: 'Active Leads', value: 142, unit: 'leads', trend: 15, sparkline: [98, 105, 115, 125, 132, 138, 142] },
      { label: 'Close Rate', value: '38%', trend: 6, sparkline: [32, 33, 34, 35, 36, 37, 38] },
      { label: 'Avg Deal Size', value: '$32K', trend: 10, sparkline: [28, 29, 30, 30.5, 31, 31.5, 32] },
    ],
  },
  {
    department: 'Marketing',
    icon: 'megaphone',
    kpis: [
      { label: 'Monthly Ad Spend', value: '$38K', trend: 8, sparkline: [32, 33.5, 34.8, 35.5, 36.2, 37.1, 38] },
      { label: 'ROAS', value: '4.2x', trend: 12, sparkline: [3.2, 3.4, 3.6, 3.8, 4.0, 4.1, 4.2] },
      { label: 'Organic Leads', value: 45, unit: 'leads', trend: 18, sparkline: [24, 28, 32, 36, 39, 42, 45] },
      { label: 'GBP Rating', value: '4.8★', trend: 2, sparkline: [4.5, 4.6, 4.65, 4.7, 4.75, 4.77, 4.8] },
    ],
  },
  {
    department: 'Operations',
    icon: 'clipboard-list',
    kpis: [
      { label: 'Active Projects', value: 38, unit: 'projects', trend: 5, sparkline: [32, 33, 34, 35, 36, 37, 38] },
      { label: 'On-Time Rate', value: '84%', trend: 3, sparkline: [78, 79, 80, 81, 82, 83, 84] },
      { label: 'Active Subs', value: 84, unit: 'subs', trend: 6, sparkline: [74, 76, 78, 80, 81, 82, 84] },
      { label: 'Avg Duration', value: '18 days', trend: -8, sparkline: [22, 21, 20.5, 19.8, 19.2, 18.5, 18] },
    ],
  },
  {
    department: 'Finance',
    icon: 'wallet',
    kpis: [
      { label: 'Monthly Revenue', value: '$980K', trend: 12, sparkline: [800, 850, 880, 920, 950, 965, 980] },
      { label: 'Collection Rate', value: '92%', trend: 4, sparkline: [85, 87, 88, 89, 90, 91, 92] },
      { label: 'Outstanding AR', value: '$245K', trend: -15, sparkline: [320, 310, 295, 280, 265, 255, 245] },
      { label: 'Commissions Due', value: '$42K', trend: 15, sparkline: [30, 32, 35, 37, 39, 40.5, 42] },
    ],
  },
  {
    department: 'Procurement',
    icon: 'package',
    kpis: [
      { label: 'Suppliers Tracked', value: 18, unit: 'suppliers', trend: 12, sparkline: [12, 13, 14, 15, 16, 17, 18] },
      { label: 'Avg Material Savings', value: '11%', trend: 4, sparkline: [8, 8.5, 9, 9.5, 10, 10.5, 11] },
      { label: 'Open POs', value: 14, unit: 'orders', trend: 8, sparkline: [10, 11, 11.5, 12, 12.5, 13, 14] },
      { label: 'Supply Alerts', value: 3, unit: 'alerts', trend: -20, sparkline: [8, 7, 6, 5, 4, 3.5, 3] },
    ],
  },
  {
    department: 'Executive',
    icon: 'briefcase',
    kpis: [
      { label: 'Action Items', value: 4, unit: 'items', trend: -20, sparkline: [7, 6.5, 6, 5.5, 5, 4.5, 4] },
      { label: 'Departments Reporting', value: 6, unit: 'depts', trend: 0, sparkline: [6, 6, 6, 6, 6, 6, 6] },
      { label: 'Daily Agent Runs', value: 47, unit: 'runs', trend: 5, sparkline: [40, 41, 42, 43, 44, 45.5, 47] },
      { label: 'Success Rate', value: '96%', trend: 2, sparkline: [92, 93, 94, 94.5, 95, 95.5, 96] },
    ],
  },
];
