import { Agent, ExecutionLog, DepartmentMetrics } from './types';

export const agents: Agent[] = [
  {
    id: 'lead-pipeline',
    name: 'Lead Pipeline',
    department: 'Sales',
    description: 'Daily scanning, prioritization, and pipeline report delivery. Updates CRM events and sends briefings.',
    status: 'idle',
    schedule: 'Every day at 08:00',
    lastRun: '2026-03-21T08:00:00Z',
    nextRun: '2026-03-22T08:00:00Z',
    icon: 'target',
    metrics: [
      { label: 'Leads Processed', value: 47, trend: 12 },
      { label: 'Follow-ups Sent', value: 18, trend: 5 },
      { label: 'Conversion Rate', value: '24%', trend: 3 },
    ],
  },
  {
    id: 'linkedin-outreach',
    name: 'LinkedIn Outreach',
    department: 'Sales',
    description: 'Finds target segments, writes personalized messages, sends them via LinkedIn, and tracks responses.',
    status: 'running',
    schedule: 'Every day at 09:30',
    lastRun: '2026-03-21T09:30:00Z',
    nextRun: '2026-03-22T09:30:00Z',
    icon: 'send',
    metrics: [
      { label: 'Messages Sent', value: 312, trend: 8 },
      { label: 'Response Rate', value: '19%', trend: 2 },
      { label: 'Meetings Booked', value: 11, trend: 15 },
    ],
  },
  {
    id: 'recruiter',
    name: 'Recruiting Pipeline',
    department: 'HR',
    description: 'Posts jobs, boosts listings, screens applications, and manages candidate pipeline.',
    status: 'scheduled',
    schedule: 'Every Monday at 10:00',
    lastRun: '2026-03-17T10:00:00Z',
    nextRun: '2026-03-24T10:00:00Z',
    icon: 'users',
    metrics: [
      { label: 'Positions Open', value: 3, trend: 0 },
      { label: 'Applications Reviewed', value: 86, trend: 22 },
      { label: 'Interviews Scheduled', value: 7, trend: 40 },
    ],
  },
  {
    id: 'invoicing',
    name: 'Client Invoicing',
    department: 'Finance',
    description: 'Generates end-of-month invoices, timesheet reports, and billing summaries for all active clients.',
    status: 'idle',
    schedule: 'Last day of month at 09:00',
    lastRun: '2026-02-28T09:00:00Z',
    nextRun: '2026-03-31T09:00:00Z',
    icon: 'receipt',
    metrics: [
      { label: 'Invoices Generated', value: 12, trend: 0 },
      { label: 'Total Billed', value: '₪148K', trend: 6 },
      { label: 'Avg Processing Time', value: '4 min', trend: -20 },
    ],
  },
  {
    id: 'receipts',
    name: 'Receipt Matching',
    department: 'Finance',
    description: 'Matches bank transactions and credit card charges to invoices. Uploads to accounting and flags missing receipts.',
    status: 'idle',
    schedule: 'Every Sunday at 07:00',
    lastRun: '2026-03-16T07:00:00Z',
    nextRun: '2026-03-23T07:00:00Z',
    icon: 'file-check',
    metrics: [
      { label: 'Transactions Matched', value: 94, trend: 8 },
      { label: 'Match Rate', value: '91%', trend: 3 },
      { label: 'Flagged Missing', value: 8, trend: -12 },
    ],
  },
  {
    id: 'social-posts',
    name: 'Social Content',
    department: 'Marketing',
    description: 'Creates daily multi-platform social media content for LinkedIn, Instagram, Facebook, and X.',
    status: 'idle',
    schedule: 'Every day at 07:30',
    lastRun: '2026-03-21T07:30:00Z',
    nextRun: '2026-03-22T07:30:00Z',
    icon: 'megaphone',
    metrics: [
      { label: 'Posts Created', value: 142, trend: 5 },
      { label: 'Engagement Rate', value: '4.2%', trend: 11 },
      { label: 'Reach', value: '28K', trend: 18 },
    ],
  },
];

export const executionLogs: ExecutionLog[] = [
  {
    id: 'log-001',
    agentId: 'linkedin-outreach',
    agentName: 'LinkedIn Outreach',
    department: 'Sales',
    startedAt: '2026-03-21T09:30:00Z',
    completedAt: '2026-03-21T09:47:22Z',
    status: 'success',
    summary: 'Sent 15 personalized outreach messages to SaaS CTOs segment',
    details: [
      'Loaded segment: SaaS CTOs (Israel, 50-200 employees)',
      'Generated 15 personalized connection messages',
      'Sent all 15 messages via LinkedIn',
      'Updated tracking in Notion CRM',
      'Sent summary email to michal@msapps.co.il',
      '3 responses received from previous batch',
    ],
    outputCount: 15,
  },
  {
    id: 'log-002',
    agentId: 'lead-pipeline',
    agentName: 'Lead Pipeline',
    department: 'Sales',
    startedAt: '2026-03-21T08:00:00Z',
    completedAt: '2026-03-21T08:12:45Z',
    status: 'success',
    summary: 'Daily pipeline scan completed — 4 hot leads identified, briefing sent',
    details: [
      'Scanned 47 active leads across all stages',
      'Identified 4 hot leads requiring immediate follow-up',
      'Updated priority scores based on recent interactions',
      'Generated daily briefing report',
      'Sent briefing via email with action items',
      'Updated calendar events for 2 follow-up meetings',
    ],
    outputCount: 4,
  },
  {
    id: 'log-003',
    agentId: 'social-posts',
    agentName: 'Social Content',
    department: 'Marketing',
    startedAt: '2026-03-21T07:30:00Z',
    completedAt: '2026-03-21T07:38:15Z',
    status: 'success',
    summary: 'Created 4 posts across LinkedIn, Instagram, Facebook, and X',
    details: [
      'Generated LinkedIn article: "Why Managed Ops Beats Hiring"',
      'Created Instagram carousel: 5 slides on automation ROI',
      'Drafted Facebook post with engagement hook',
      'Composed X thread: 4 tweets on operational efficiency',
    ],
    outputCount: 4,
  },
  {
    id: 'log-004',
    agentId: 'recruiter',
    agentName: 'Recruiting Pipeline',
    department: 'HR',
    startedAt: '2026-03-17T10:00:00Z',
    completedAt: '2026-03-17T10:34:50Z',
    status: 'success',
    summary: 'Weekly recruiting cycle — reviewed 23 applications, scheduled 3 interviews',
    details: [
      'Boosted job postings on AllJobs and Goozali',
      'Screened 23 new applications for Senior Developer role',
      'Shortlisted 5 candidates based on criteria match',
      'Sent rejection emails to 18 non-matching candidates',
      'Scheduled 3 first-round interviews',
      'Updated recruiting spreadsheet with all statuses',
    ],
    outputCount: 23,
  },
  {
    id: 'log-005',
    agentId: 'receipts',
    agentName: 'Receipt Matching',
    department: 'Finance',
    startedAt: '2026-03-16T07:00:00Z',
    completedAt: '2026-03-16T07:22:10Z',
    status: 'partial',
    summary: 'Matched 41 of 45 transactions — 4 receipts missing, flagged for review',
    details: [
      'Pulled 45 unmatched transactions from iCount',
      'Searched Zoho Mail for corresponding invoices',
      'Successfully matched 41 transactions',
      'Uploaded 41 receipts to iCount',
      'Flagged 4 missing receipts in Google Doc',
      'Sent summary to michal@msapps.co.il for manual review',
    ],
    outputCount: 41,
  },
  {
    id: 'log-006',
    agentId: 'invoicing',
    agentName: 'Client Invoicing',
    department: 'Finance',
    startedAt: '2026-02-28T09:00:00Z',
    completedAt: '2026-02-28T09:18:33Z',
    status: 'success',
    summary: 'Generated 12 invoices totaling ₪148,200 for February',
    details: [
      'Pulled timesheet data from Monday.com for all active clients',
      'Calculated billable hours per client and project',
      'Generated 12 PDF invoices with correct rates',
      'Created summary report with breakdown by client',
      'Sent invoices via email to client contacts',
      'Updated accounting records in iCount',
    ],
    outputCount: 12,
  },
  {
    id: 'log-007',
    agentId: 'lead-pipeline',
    agentName: 'Lead Pipeline',
    department: 'Sales',
    startedAt: '2026-03-20T08:00:00Z',
    completedAt: '2026-03-20T08:11:20Z',
    status: 'success',
    summary: 'Daily pipeline scan — 2 leads moved to proposal stage',
    details: [
      'Scanned 45 active leads',
      'Identified 2 leads ready for proposals',
      'Updated CRM with latest interaction notes',
      'Sent daily briefing to team',
    ],
    outputCount: 2,
  },
  {
    id: 'log-008',
    agentId: 'linkedin-outreach',
    agentName: 'LinkedIn Outreach',
    department: 'Sales',
    startedAt: '2026-03-20T09:30:00Z',
    completedAt: '2026-03-20T09:44:18Z',
    status: 'success',
    summary: 'Sent 12 messages to Fintech founders segment',
    details: [
      'Loaded segment: Fintech Founders (Tel Aviv)',
      'Generated 12 personalized messages',
      'Sent all via LinkedIn',
      'Updated Notion tracking',
    ],
    outputCount: 12,
  },
];

export const departmentMetrics: DepartmentMetrics[] = [
  {
    department: 'Sales',
    icon: 'trending-up',
    kpis: [
      { label: 'Pipeline Value', value: '₪2.4M', trend: 14, sparkline: [180, 195, 210, 220, 235, 260, 280] },
      { label: 'Leads This Month', value: 142, unit: 'leads', trend: 8, sparkline: [98, 105, 112, 118, 125, 134, 142] },
      { label: 'Outreach Sent', value: 312, unit: 'messages', trend: 12, sparkline: [220, 240, 255, 270, 285, 298, 312] },
      { label: 'Meetings Booked', value: 23, unit: 'meetings', trend: 15, sparkline: [12, 14, 16, 17, 19, 21, 23] },
    ],
  },
  {
    department: 'HR',
    icon: 'users',
    kpis: [
      { label: 'Open Positions', value: 3, trend: 0, sparkline: [4, 4, 3, 3, 3, 3, 3] },
      { label: 'Applications This Month', value: 86, unit: 'apps', trend: 22, sparkline: [45, 52, 58, 65, 72, 79, 86] },
      { label: 'Interview Rate', value: '8.1%', trend: 5, sparkline: [6, 6.2, 6.8, 7.1, 7.5, 7.8, 8.1] },
      { label: 'Time to Fill', value: '18 days', trend: -10, sparkline: [24, 23, 22, 21, 20, 19, 18] },
    ],
  },
  {
    department: 'Finance',
    icon: 'wallet',
    kpis: [
      { label: 'Monthly Revenue', value: '₪148K', trend: 6, sparkline: [120, 125, 130, 135, 138, 142, 148] },
      { label: 'Receipt Match Rate', value: '91%', trend: 3, sparkline: [82, 84, 86, 87, 89, 90, 91] },
      { label: 'Invoices Processed', value: 12, unit: 'invoices', trend: 0, sparkline: [11, 12, 11, 12, 12, 12, 12] },
      { label: 'Processing Time', value: '4 min', trend: -20, sparkline: [8, 7, 6.5, 6, 5.5, 4.5, 4] },
    ],
  },
  {
    department: 'Marketing',
    icon: 'megaphone',
    kpis: [
      { label: 'Posts Published', value: 142, unit: 'posts', trend: 5, sparkline: [110, 115, 120, 125, 130, 136, 142] },
      { label: 'Total Reach', value: '28K', trend: 18, sparkline: [15, 17, 19, 21, 23, 25, 28] },
      { label: 'Engagement Rate', value: '4.2%', trend: 11, sparkline: [3.0, 3.2, 3.5, 3.7, 3.9, 4.0, 4.2] },
      { label: 'Followers Gained', value: 340, unit: 'followers', trend: 24, sparkline: [180, 200, 230, 260, 285, 310, 340] },
    ],
  },
];
